// Code generated by go-tablelist-codegen. DO NOT EDIT.

package tablelist

var UserPointsTable = struct {
	TableName string
	UserId string
	Points string
	CreatedAt string
	UpdatedAt string
}{
	TableName: "user_points",
	UserId: "user_id",
	Points: "points",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

var UsersTable = struct {
	TableName string
	Id string
	Email string
	Name string
	CreatedAt string
	UpdatedAt string
	DeletedAt string
}{
	TableName: "users",
	Id: "id",
	Email: "email",
	Name: "name",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	DeletedAt: "deleted_at",
}
