name: Go CI
on: [ push, pull_request ]
permissions:
  checks: write

jobs:
  define-go-versions:
    name: Define Go Versions
    runs-on: ubuntu-latest
    outputs:
      go-versions: ${{ steps.set.outputs.go-versions }}
    steps:
      - id: define
        run: echo 'go-versions=[ "1.25", "1.26" ]' >> "$GITHUB_OUTPUT"

  test:
    needs: define-go-versions
    name: Test
    strategy:
      fail-fast: false
      matrix:
        go-version: ${{ fromJson(needs.define-go-versions.outputs.go-versions) }}
    uses: Siroshun09/gh-actions-workflows/.github/workflows/go-test.yml@v1
    with:
      check-name: Test Report (Go ${{ matrix.go-version }})
      upload-results: true
      go-version: ${{ matrix.go-version }}

  lint:
    uses: Siroshun09/gh-actions-workflows/.github/workflows/go-lint.yml@v1
    with:
      golangci-lint-version: v2.12.2
