name: Go CI
on: [ push, pull_request ]
permissions:
  checks: write

jobs:
  define-go-versions:
    name: Define Go Versions
    runs-on: ubuntu-latest
    outputs:
      go-versions: ${{ steps.define.outputs.go-versions }}
    steps:
      - id: define
        run: echo 'go-versions=[ "1.25", "1.26" ]' >> "$GITHUB_OUTPUT"

  test:
    needs: define-go-versions
    name: Test
    strategy:
      fail-fast: false
      matrix:
        go-version: ${{ fromJson(needs.define-go-versions.outputs.go-versions) }}
    uses: Siroshun09/gh-actions-workflows/.github/workflows/go-test.yml@v1
    with:
      check-name: Test Report (Go ${{ matrix.go-version }})
      upload-results: true
      go-version: ${{ matrix.go-version }}

  test-mysql:
    needs: define-go-versions
    name: Test for MySQL
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ${{ fromJson(needs.define-go-versions.outputs.go-versions) }}
    services:
      mariadb:
        image: mariadb:12.2.2@sha256:b3af559fc38e013c50dd5b5993bfbbb21125c1a62d976b3b0a14d9c4acaae578
        ports:
          - "3306:3306"
        env:
          MYSQL_DATABASE: tablelist_db
          MYSQL_ROOT_PASSWORD: tablelist_pw
        options: >-
          --health-cmd "healthcheck.sh --connect --innodb_initialized"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: Siroshun09/gh-actions-workflows/.github/actions/checkout@v1
      - uses: Siroshun09/gh-actions-workflows/.github/actions/go-setup@v1
        with:
          go-version: ${{ matrix.go-version }}
      - uses: Siroshun09/gh-actions-workflows/.github/actions/go-test@v1
        with:
          additional-arguments: "-run ^TestMySQL$"
          check-name: Test Report for MySQL (Go ${{ matrix.go-version }})
          upload-results: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          ENABLE_MYSQL_TEST: true
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          MYSQL_USER: root
          MYSQL_PASSWORD: tablelist_pw
          MYSQL_DATABASE: tablelist_db

  lint:
    uses: Siroshun09/gh-actions-workflows/.github/workflows/go-lint.yml@v1
    with:
      golangci-lint-version: v2.12.2
